### PR TITLE
Merging in upstream

### PR DESCRIPTION
**Pull request by piratebriggs**
I've pulled in the latest commits from upstream and made some required changes as the contract with the zprobe classes has changed.

I've compiled these and am using them on a MKS SBase 1.3 successfully.

Sorry for the pre-mature PR yesterday!

### CODE REVIEW

**Comment by macaba** [comment]
I don't have time to test this currently; is your confidence level high that this is fully working?
Out of interest: what are the best new features/fixes that we get from merging upstream?

**Comment by piratebriggs** [comment]
Well, it's what I'm running on my Mini Kossel currently - LSQ is the only sane levelling strategy that I've found. I'd like to PR it into the core but that would need David's blessing I guess.

As for new features, they don't publish release notes - I just didn't want this fork to stagnate as it's what I use personally. As it happens I did have to make some small edits to make it compatible so glad I did it (fef5d34883f3aad9f0f71d48de037a7c713cc913)

**Comment by macaba** [comment]
Good enough for me! I concur with your thoughts on LSQ - it just _works._

**Comment by macaba** [comment]
Thank you @piratebriggs. 👍

**Pull request merged**
